---
name: Odoo Inventory ETL

"on":
  schedule:
    # Runs once daily at 00:15 UTC (3:15 AM Riyadh time) - Historical inventory
    - cron: '15 0 * * *'
    # Runs once daily at 18:00 UTC (9:00 PM Riyadh time)
    # End of business day stock snapshot
    - cron: '0 18 * * *'
  workflow_dispatch:  # Allows you to run it manually from the Actions tab
    inputs:
      script_type:
        description: 'Choose which script to run'
        required: true
        default: 'both'
        type: choice
        options:
          - both
          - inventory_history
          - stock_snapshot

jobs:
  run-inventory-history:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'schedule' &&
      github.event.schedule == '15 0 * * *' ||
      (github.event_name == 'workflow_dispatch' &&
       (github.event.inputs.script_type == 'both' ||
        github.event.inputs.script_type == 'inventory_history'))

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create credentials file from secret
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json
        shell: bash

      - name: Run Inventory History ETL script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: 'gcp-key.json'
          ODOO_PASSWORD: ${{ secrets.ODOO_PASSWORD }}
        run: python inventory_etl.py

  run-stock-snapshot:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'schedule' &&
      github.event.schedule == '0 18 * * *' ||
      (github.event_name == 'workflow_dispatch' &&
       (github.event.inputs.script_type == 'both' ||
        github.event.inputs.script_type == 'stock_snapshot'))

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create credentials file from secret
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json
        shell: bash

      - name: Run Stock Snapshot ETL script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: 'gcp-key.json'
          ODOO_PASSWORD: ${{ secrets.ODOO_PASSWORD }}
        run: python stock_etl.py
